//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradeChecker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GradeChecker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMEI	Model	Color	XPO grade	VZW Grade	DEFECTS FOUND	FD Grade	FD Grade
        ///356989067574909	APL6	GOLD	C	C	&gt; 16 DEFECTS ON B	D+	
        ///356991068618370	APL6	GOLD	C	C	DISCLORATION ON SILENT KEY AND BACK BOT	B	
        ///354410066536072	APL6	GOLD	C	C	PIN SIZE DEFECTS ON ENTIRE BACK	B	
        ///359234067438301	APL6	GOLD	C	B	&lt;16 DEFECTS ON B AND 1 SCRATCH ON AA	D+	
        ///358369063219288	APL6	GOLD	C	C	&gt;16 DEFECTS ON B SIDES;DISCOLORATION ON SILENT KEY	D+	
        ///359230065530123	APL6	GOLD	C	C	DISC ON BACK AND SMALL NICKS ON BACK	B	
        ///359306062631963	APL6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string verizon_data {
            get {
                return ResourceManager.GetString("verizon_data", resourceCulture);
            }
        }
    }
}
