//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradeChecker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GradeChecker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scratch-AA-S
        ///Scratch-AA-Minor
        ///Scratch-AA-Major
        ///Scratch-AA-Other2
        ///Scratch-AA-Other1
        ///Scratch-A-S1
        ///Scratch-A-S2
        ///Scratch-A-Minor
        ///Scratch-A-Major
        ///Scratch-A-Other3
        ///Scratch-A-Other2
        ///Scratch-A-Other1
        ///Scratch-A-WearedHomeButton
        ///Scratch-B-S1
        ///Scratch-B-S2
        ///Scratch-B-Minor
        ///Scratch-B-Major
        ///Scratch-B-Other3
        ///Scratch-B-Other2
        ///Scratch-B-Other1
        ///Scratch-C-S1
        ///Scratch-C-S2
        ///Scratch-C-Minor
        ///Scratch-C-Major
        ///Scratch-C-Other3
        ///Scratch-C-Other2
        ///Scratch-C-Other1
        ///Nick-AA-S
        ///Nick-AA-Minor
        ///Nick-AA-Major
        ///Nick-AA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string grade_keys {
            get {
                return ResourceManager.GetString("grade_keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;score&gt;
        ///  &lt;Scratch_AA&gt;1000&lt;/Scratch_AA&gt;
        ///  &lt;Scratch_A&gt;1000&lt;/Scratch_A&gt;
        ///  &lt;Scratch_B&gt;1000&lt;/Scratch_B&gt;
        ///  &lt;Nick_AA&gt;1000&lt;/Nick_AA&gt;
        ///  &lt;Nick_A&gt;1000&lt;/Nick_A&gt;
        ///  &lt;Nick_B&gt;1000&lt;/Nick_B&gt;
        ///  &lt;Discoloration_AA&gt;1000&lt;/Discoloration_AA&gt;
        ///  &lt;Discoloration_A&gt;1000&lt;/Discoloration_A&gt;
        ///  &lt;Discoloration_B&gt;1000&lt;/Discoloration_B&gt;
        ///  &lt;PinDotGroup_A&gt;1000&lt;/PinDotGroup_A&gt;
        ///  &lt;PinDotGroup_B&gt;1000&lt;/PinDotGroup_B&gt;
        ///&lt;/score&gt;.
        /// </summary>
        internal static string score {
            get {
                return ResourceManager.GetString("score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;A+&quot;:
        ///    {
        ///      &quot;all_all_all&quot;: 3,
        ///      &quot;Scratch-AA-S&quot;: 1,
        ///      &quot;Scratch-AA-Other1&quot;: 0,
        ///      &quot;Nick-AA-S&quot;: 0,
        ///      &quot;Nick-AA-Other1&quot;: 0,
        ///      &quot;Crack-AA-A-Glass&quot;: 0,
        ///      &quot;Discoloration-AA&quot;: 0,
        ///      &quot;Scratch-A-S1&quot;: 3,
        ///      &quot;Scratch-A-Other1&quot;: 0,
        ///      &quot;Scratch-A-WearedHomeButton&quot;: 0,
        ///      &quot;Nick-A-S&quot;: 0,
        ///      &quot;Nick-A-Other1&quot;: 0,
        ///      &quot;Discoloration-A-S&quot;: 0,
        ///      &quot;Discoloration-A-Other1&quot;: 0,
        ///      &quot;Scratch-B-S1&quot;: 3,
        ///      &quot;Scratch-B-Other1&quot;: 0,
        ///      &quot;Nick-B-S&quot;: 0,
        ///      &quot;Nic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string spec_keys {
            get {
                return ResourceManager.GetString("spec_keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMEI	Model	Color	XPO grade	VZW Grade	FD New Grade	New Comments	Selected	Re-Scan	FD/VZW	Matching %	FD/XPO	Matching %												
        ///356989067574909	APL6	GOLD	C	C	C				1	50.00%	1	60.00%												
        ///356991068618370	APL6	GOLD	C	C	D+				0		0													
        ///354410066536072	APL6	GOLD	C	C	C				1		1													
        ///359234067438301	APL6	GOLD	C	B	C	Too many deep nicks on B. D+	1		0		1													
        ///358369063219288	APL6	GOLD	C	C	C	Too many deep nicks on B. D+	1		1		1													
        ///359230065530123	APL6	GOLD	C	C	D+	Missed wh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string verizon_data {
            get {
                return ResourceManager.GetString("verizon_data", resourceCulture);
            }
        }
    }
}
